from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('chw_file', models.FileField(upload_to='uploads/chw/')),
                ('supervision_file', models.FileField(upload_to='uploads/supervision/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={'ordering': ['-year', '-month', '-week_start_date'], 'verbose_name': 'Upload Batch', 'verbose_name_plural': 'Upload Batches'},
        ),
        migrations.CreateModel(
            name='CHWRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('community_health_unit', models.CharField(max_length=200)),
                ('chp_area', models.CharField(blank=True, max_length=200)),
                ('chw_name', models.CharField(max_length=200)),
                ('chw_id', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_hhs', models.IntegerField(default=0)),
                ('hh_visits', models.IntegerField(default=0)),
                ('new_hhs_registered', models.IntegerField(default=0)),
                ('pregnancies_registered', models.IntegerField(default=0)),
                ('active_pregnancies', models.IntegerField(default=0)),
                ('pregnancies_visited', models.IntegerField(default=0)),
                ('pregnancy_visits', models.IntegerField(default=0)),
                ('anc_total_deliveries', models.IntegerField(default=0)),
                ('deliveries_4plus_anc', models.IntegerField(default=0)),
                ('deliveries_with_anc_data', models.IntegerField(default=0)),
                ('first_trimester_registrations', models.IntegerField(default=0)),
                ('iron_folate_count', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('facility_deliveries', models.IntegerField(default=0)),
                ('pnc_48hr_ontime', models.IntegerField(default=0)),
                ('pnc_3_7d_ontime', models.IntegerField(default=0)),
                ('iccm_assessments', models.IntegerField(default=0)),
                ('positive_diagnoses_u5', models.IntegerField(default=0)),
                ('treated_visits_u5', models.IntegerField(default=0)),
                ('malaria_diagnosed', models.IntegerField(default=0)),
                ('pneumonia_diagnosed', models.IntegerField(default=0)),
                ('diarrhea_diagnosed', models.IntegerField(default=0)),
                ('malaria_managed', models.IntegerField(default=0)),
                ('pneumonia_managed', models.IntegerField(default=0)),
                ('diarrhea_managed', models.IntegerField(default=0)),
                ('danger_sign_referred', models.IntegerField(default=0)),
                ('fever_cases', models.IntegerField(default=0)),
                ('fever_tested_rdt', models.IntegerField(default=0)),
                ('iccm_referrals_total', models.IntegerField(default=0)),
                ('iccm_referral_followup', models.IntegerField(default=0)),
                ('iccm_referrals_u2mo', models.IntegerField(default=0)),
                ('iccm_completed_referrals_u2mo', models.IntegerField(default=0)),
                ('u1_positive_diagnoses', models.IntegerField(default=0)),
                ('u1_treated_visits', models.IntegerField(default=0)),
                ('u1_sick_assessments', models.IntegerField(default=0)),
                ('iz_assessments', models.IntegerField(default=0)),
                ('iz_fully_immunized', models.IntegerField(default=0)),
                ('iz_children_9_23mo', models.IntegerField(default=0)),
                ('iz_defaulters', models.IntegerField(default=0)),
                ('iz_defaulters_followed', models.IntegerField(default=0)),
                ('iz_defaulters_completed', models.IntegerField(default=0)),
                ('fp_assessments', models.IntegerField(default=0)),
                ('fp_new_users', models.IntegerField(default=0)),
                ('fp_unique_new_users', models.IntegerField(default=0)),
                ('fp_current_users', models.IntegerField(default=0)),
                ('fp_wra_assessed', models.IntegerField(default=0)),
                ('fp_cyp', models.IntegerField(default=0)),
                ('fp_non_users_assessed', models.IntegerField(default=0)),
                ('fp_needing_refill', models.IntegerField(default=0)),
                ('fp_refilled', models.IntegerField(default=0)),
                ('fp_referred', models.IntegerField(default=0)),
                ('fp_referral_followup', models.IntegerField(default=0)),
                ('fp_current_users_18_49', models.IntegerField(default=0)),
                ('fp_wra_assessed_18_49', models.IntegerField(default=0)),
                ('nutrition_assessments', models.IntegerField(default=0)),
                ('muac_screened', models.IntegerField(default=0)),
                ('mam_sam_total', models.IntegerField(default=0)),
                ('mam_sam_referred', models.IntegerField(default=0)),
                ('mam_sam_referral_completed', models.IntegerField(default=0)),
                ('exclusive_bf', models.IntegerField(default=0)),
                ('u6mo_bf_assessed', models.IntegerField(default=0)),
                ('complementary_feeding', models.IntegerField(default=0)),
                ('assessed_6_9mo', models.IntegerField(default=0)),
                ('vitamin_a_covered', models.IntegerField(default=0)),
                ('assessed_6_59mo_vita', models.IntegerField(default=0)),
                ('days_synced', models.IntegerField(default=0)),
                ('supervised', models.BooleanField(default=False)),
                ('supervision_visits', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chw_records', to='dashboard.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('community_health_unit', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('chv_name', models.CharField(max_length=200)),
                ('chv_uuid', models.CharField(blank=True, max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('visit_sections', models.TextField(blank=True)),
                ('has_essential_medicines', models.BooleanField(blank=True, null=True)),
                ('medicines_lacking', models.FloatField(blank=True, null=True)),
                ('assessment_score', models.FloatField(blank=True, null=True)),
                ('assessment_denominator', models.IntegerField(default=0)),
                ('has_all_tools', models.BooleanField(blank=True, null=True)),
                ('has_ppe', models.BooleanField(blank=True, null=True)),
                ('supervisor_area', models.CharField(blank=True, max_length=200)),
                ('supervisor_phone', models.CharField(blank=True, max_length=50)),
                ('next_steps', models.TextField(blank=True)),
                ('overall_observations', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_records', to='dashboard.uploadbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'county'], name='dashboard_c_batch_i_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'county', 'sub_county'], name='dashboard_c_batch_s_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'county', 'sub_county', 'community_health_unit'], name='dashboard_c_batch_c_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['is_active'], name='dashboard_c_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionrecord',
            index=models.Index(fields=['batch', 'county'], name='dashboard_s_batch_i_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionrecord',
            index=models.Index(fields=['batch', 'county', 'sub_county'], name='dashboard_s_batch_s_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionrecord',
            index=models.Index(fields=['batch', 'county', 'sub_county', 'community_health_unit'], name='dashboard_s_batch_c_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionrecord',
            index=models.Index(fields=['visit_date'], name='dashboard_s_visit_d_idx'),
        ),
    ]
