# Generated by Django 4.2.13 on 2026-05-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chwrecord',
            new_name='dashboard_c_batch_i_527415_idx',
            old_name='dashboard_c_batch_i_idx',
        ),
        migrations.RenameIndex(
            model_name='chwrecord',
            new_name='dashboard_c_batch_i_d89c95_idx',
            old_name='dashboard_c_batch_s_idx',
        ),
        migrations.RenameIndex(
            model_name='chwrecord',
            new_name='dashboard_c_batch_i_50b637_idx',
            old_name='dashboard_c_batch_c_idx',
        ),
        migrations.RenameIndex(
            model_name='chwrecord',
            new_name='dashboard_c_is_acti_340b7f_idx',
            old_name='dashboard_c_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisionrecord',
            new_name='dashboard_s_batch_i_a84680_idx',
            old_name='dashboard_s_batch_i_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisionrecord',
            new_name='dashboard_s_batch_i_d2e2d4_idx',
            old_name='dashboard_s_batch_s_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisionrecord',
            new_name='dashboard_s_batch_i_b0a32a_idx',
            old_name='dashboard_s_batch_c_idx',
        ),
        migrations.RenameIndex(
            model_name='supervisionrecord',
            new_name='dashboard_s_visit_d_56e1bf_idx',
            old_name='dashboard_s_visit_d_idx',
        ),
        migrations.AlterField(
            model_name='supervisionrecord',
            name='medicines_lacking',
            field=models.TextField(blank=True, default=''),
        ),
    ]
