# Generated by Django 4.2.13 on 2026-05-07 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_rename_dashboard_c_batch_i_idx_dashboard_c_batch_i_527415_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('week_start_date', models.DateField(blank=True, null=True)),
                ('sync_file', models.FileField(upload_to='uploads/sync/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Upload Batch',
                'verbose_name_plural': 'Sync Upload Batches',
                'ordering': ['-year', '-month', '-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='CHPSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('community_health_unit', models.CharField(max_length=200)),
                ('chp_name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('days_synced', models.IntegerField(default=0)),
                ('reports_synced', models.IntegerField(default=0)),
                ('last_sync_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='dashboard.syncuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'county'], name='sync_batch_county_idx'), models.Index(fields=['batch', 'county', 'sub_county'], name='sync_batch_sc_idx'), models.Index(fields=['batch', 'county', 'sub_county', 'community_health_unit'], name='sync_batch_chu_idx')],
            },
        ),
    ]
