# Generated by Django 4.2.13 on 2026-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_syncuploadbatch_chpsyncrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chwrecord',
            name='num_u5_assessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chwrecord',
            name='registered_children_u2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chwrecord',
            name='registered_children_u5',
            field=models.IntegerField(default=0),
        ),
    ]
