# Generated by Django 4.2.13 on 2026-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chwrecord_num_u5_assessed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncuploadbatch',
            name='sync_file',
        ),
        migrations.AddField(
            model_name='syncuploadbatch',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
