# Generated by Django 4.2.13 on 2026-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_syncuploadbatch_sync_file_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'is_active'], name='dashboard_c_batch_i_732f55_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'is_active', 'county'], name='dashboard_c_batch_i_b7a015_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'is_active', 'supervised'], name='dashboard_c_batch_i_992e63_idx'),
        ),
        migrations.AddIndex(
            model_name='chwrecord',
            index=models.Index(fields=['batch', 'is_active', 'supervision_visits'], name='dashboard_c_batch_i_41d2c6_idx'),
        ),
    ]
