# Generated by Django 4.2.13 on 2026-07-07 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_chwrecord_dashboard_c_batch_i_732f55_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kpi_reports/')),
                ('report_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Latest month in this report')),
                ('report_year', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_year', '-report_month'],
            },
        ),
        migrations.CreateModel(
            name='KPIDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metric_key', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='dashboard.kpireport')),
            ],
            options={
                'indexes': [models.Index(fields=['county', 'sub_county', 'metric_key', 'year', 'month'], name='kpi_lookup_idx')],
                'unique_together': {('report', 'county', 'sub_county', 'metric_key', 'year', 'month')},
            },
        ),
    ]
