# Generated by Django 4.2.13 on 2026-08-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dashutilreport_dashutildatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashutildatapoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashutilreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dashutilreport',
            name='period_label',
            field=models.CharField(help_text='e.g. July 2026 or 2026-W34', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashutilreport',
            name='week',
            field=models.IntegerField(blank=True, help_text='ISO week number', null=True),
        ),
    ]
