# Generated by Django 4.2.13 on 2026-09-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0009_alter_dashutildatapoint_id_alter_dashutilreport_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chwrecord",
            name="diarrhea_referred",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chwrecord",
            name="malaria_referred",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chwrecord",
            name="pneumonia_referred",
            field=models.IntegerField(default=0),
        ),
    ]
