# Generated by Django 4.2.13 on 2026-09-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0010_chwrecord_diarrhea_referred_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EDDUploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="edd_lists/")),
                (
                    "label",
                    models.CharField(help_text="e.g. October 2026", max_length=100),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EDDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "sub_county",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "community_unit",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                (
                    "chw_name",
                    models.CharField(blank=True, db_index=True, max_length=150),
                ),
                ("chw_uuid", models.CharField(blank=True, max_length=100)),
                (
                    "pregnancy_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("member_name", models.CharField(blank=True, max_length=150)),
                ("household_name", models.CharField(blank=True, max_length=150)),
                (
                    "effective_edd_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("initial_edd_date", models.DateField(blank=True, null=True)),
                ("latest_edd_date", models.DateField(blank=True, null=True)),
                ("has_edd_shift_flag", models.BooleanField(default=False)),
                ("edd_shift_days", models.IntegerField(blank=True, null=True)),
                ("has_no_edd_captured", models.BooleanField(default=False)),
                (
                    "gestational_weeks_at_registration",
                    models.IntegerField(blank=True, null=True),
                ),
                ("chp_visit_count", models.IntegerField(blank=True, null=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dashboard.edduploadbatch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["county", "sub_county", "community_unit"],
                        name="edd_geo_idx",
                    )
                ],
            },
        ),
    ]
