# Generated by Django 4.2.13 on 2026-10-01 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0011_edduploadbatch_eddrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(db_index=True, max_length=100)),
                ("metric_key", models.CharField(db_index=True, max_length=50)),
                ("target", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["county", "metric_key"],
                "unique_together": {("county", "metric_key")},
            },
        ),
    ]
