# Generated by Django 4.2.13 on 2026-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_seed_indicator_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="chpsyncrecord",
            name="forms_recorded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chpsyncrecord",
            name="latest_form_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
